version: '3'
services:
  frontend:
    container_name: tax-fe
    build:
      context: .
      target: development
    image: tax-fe
    init: true
    ports:
      - '3000:3000'
    networks:
      - tax-network
    environment:
      NODE_ENV: development
    expose:
      - '3000'
networks:
  tax-network: